### ISSUE TITLE
Общение #2

### ISSUE THREAD

**Issue by nagayev** [nagayev/korapi#2]
Теперь общаемся тут.

**Comment by Peytob** [comment]
Так. Как я могу это протестировать? Еще чутка ковырнул класс игрока, кстати. Почти готов

**Comment by nagayev** [comment]
@Peytob Отлично!
А как класс ковырял?
А я узнал url запроса добавление лота на аукцион
Теперь экспериментирую с тирзоном кстати,так проще
@Peytob Отлично!
А как класс ковырял?
А я узнал url запроса добавление лота на аукцион
Теперь экспериментирую с тирзоном кстати,так проще
@Peytob Отлично!
А как класс ковырял?
А я узнал url запроса добавление лота на аукцион
Теперь экспериментирую с Тирзоном кстати,так проще
P.S. github не грузит картинки чет, поэтому вот она:
http://shinviyanezhnaya.kor.ru/photoalbums/image/459155

**Comment by nagayev** [comment]
@Peytob 
Еще есть интересный момент:
Просмотр заблоченной фотки
На Шинвии есть заблоченные фотки.
Через Тирзона зашелна Шинвию и посмотрел код элемента
Получил ссылку:
http://m1.kor.ru/media/gallery/thumbnails/8c6fed7e020f1ce0c9d6cc8bc6326a9c.jpg
Заменяем thumbnails на original и магия)
http://m1.kor.ru/media/gallery/originals/8c6fed7e020f1ce0c9d6cc8bc6326a9c.jpg

**Comment by nagayev** [comment]
@Peytob 
Нашел ссылку для удаления альбома:
http://shinviyanezhnaya.kor.ru/photoalbums/delete_album/?album_id=98943
в случае удачи будет написано <ok />
не забудь заменить ник на свой и id альбома

**Comment by Peytob** [comment]
Мы можем полностью сделать API управления альбомами теперь. Ну почти полностью
Я про тот, который сам писал на плюсах. Только не придумаю как ID предметов хранить - в uint32_t или в чем-то другом...

**Comment by nagayev** [comment]
@Peytob не знаю устаревшие или нет,но у меня не работают.
редирект на главную.
просто запусти установщик,открой cmd/powershell в папке с моим nodejs файлом и в консоле набери
node -v
Если покажет версию ноды,значит все круто.
Тогда набирай node название файла
Пример запуска test.js
node test
можно 
node test.js

**Comment by Peytob** [comment]
![345345](https://user-images.githubusercontent.com/38009435/39085550-c983b2da-4573-11e8-9f25-21d920528fa5.png)
Мам

**Comment by nagayev** [comment]
@Peytob
так должно быть
он не может найти модуль request-promise который я использую.
сорян, забыл это сказать.
запусти cmd и введи 
npm install request-promise
npm - пакетный менеджер nodejs
install - команда добавлнения пакета
Флаги install(главные):
--save сохраняет модуль в эту папку(использовать из другой папки нельзя)
-g сохраняет модуль глобально
Пример:
npm install -g request-promise

**Comment by Peytob** [comment]
Error in requestTypeError: Cannot read property 'slice' of undefined
После установки и npm request -save

**Comment by nagayev** [comment]
@Peytob ДААА.
У меня вышло отправить настроение)
Хз в чем проблема,это старый файл.
Новый залил в auth.js
Почитай коменты в нем

**Comment by nagayev** [comment]
@Peytob 
что нужно менять:
переменную mood(настроение)
поставить свои куки из браузера
поставить свой ник в адрес запроса(смотри 52 строку и дальше в блоке if(test){}
да,чтобы отправить настроение нужно иметь test=1,если изменить значение,то это будет попытка логина

**Comment by Peytob** [comment]
Cannot find module 'fs-sync'
Можно это статично все прицепить к этому?

**Comment by nagayev** [comment]
@Peytob 
установи fs-sync через npm(так же как request)
да,забыл сказать.
я забыл обновить код,поэтому можно писать насроение только английскими буквами.
Не понял вопроса

**Comment by Peytob** [comment]
Ну чтобы все библиотеки (или как это тут называется) шло сразу в архиве с программой

**Comment by nagayev** [comment]
@Peytob 
библиотеки или модули называется,все равно как)
можно, но пока я тестировал один необходимости не было.
других зависимостей у проекта еще долго не будет,так что смысла особо нет.

**Comment by Peytob** [comment]
И как куки из браузера поставить? Тупые вопросы, наверное :D

**Comment by nagayev** [comment]
@Peytob 
я тебе вроде рассказывал.
делаешь что-нибудь в коре с открытой консолью
Например создай запись/настроение.
В запросе будет строка Cookie
Из нее поставь в cookie
например
sbsid равно 2
поставь 2

**Comment by Peytob** [comment]
А, да. Сейчас протестируем на мулях логин и настроение

**Comment by Peytob** [comment]
Может быть потом на питоне попробую замутить что-то консольное для этого, если получится подружить его с NodeJS

**Comment by nagayev** [comment]
@Peytob 
Получилось?

**Comment by nagayev** [comment]
@Peytob обновление по поводу cookie:
__utma и __utmz обновляются,но при передаче старых данных все сохраняется.
т.е их можно не менять
tzo и _ym_uid(это вроде id Яндекс Денег кора)не меняются.

**Comment by nagayev** [comment]
@Peytob 
для отправки настроения авторизация не нужна(вроде)
только верная кука
видишь ответ?
в поле location при успешной авторизации передается твой ник
типо location: 'http://tirzon.kor.ru/'
Короче,похоже у тебя НЕПРАВИЛЬНАЯ КУКА.
Пришли свою куку(т.е содержание объекта cookie).
Не волнуйся, я не буду ничего делать с твоим аком))
Максимум настроение изменю на тоже самое(для проверки корректности куки)

**Comment by nagayev** [comment]
@Peytob и да,ты не забыл про изменение ника?
Залил обновленную версию где нужно будет менять не кучу адресов,а только
ник один раз(переменная nick)
Так же в ней можно использовать русские буквы в настроениях.
Для использования нужна либа querystring и chalk.
Рекомендую поставить chalk глобально,оч нужная либа.
Нужна для цветных сообщений в консоле.

**Comment by Peytob** [comment]
Прошло! Я только хотел про переменные предложить. Попробую изучить часть, касательную питона и NodeJS

**Comment by nagayev** [comment]
@Peytob только вот вопрос зачем?
настроение поменялось?

**Comment by Peytob** [comment]
Удобство, зачатки клиента.
http://doitbro.kor.ru/ да. Ну в общем попробую на себя змейку взять - как раз изучил основы

**Comment by nagayev** [comment]
@Peytob отправил заявку в друзья с Тирзона.
О,а настроение поменялось реал)

**Comment by nagayev** [comment]
@Peytob только вот че хреново в питоне это 
нельзя перегружать Host в requests
А без хоста мы не напишем апи.
Вообщем,нужно вдвоем на чем-то одном писать.
Так удобнее будет.

**Comment by Peytob** [comment]
Я не могу изучать два новых ЯП разом - не до этого. Почему это так плохо? Там нет никаких пространств имен или чего такого?

**Comment by nagayev** [comment]
@Peytob да,2 яп сразу это жестко.
и в питоне,и в ноде есть классы,а в ноде еще есть объекты.

**Comment by nagayev** [comment]
@Peytob 
после этого поста подумал, что нужно ограничение по кол-ву запросов в клиенте, чтобы не палить что мы с клиента.
http://amorralnyi.kor.ru/blog/comments/2805383/page/p/1#
например не более 8 запросов в секунду(не считая файлы, я считаю только страницы)

**Comment by Peytob** [comment]
Была идея сделать на вебе клиент, но смысл не вижу - делать веб-клиент на веб-игру, у которой есть веб-клиент... А не такой прожорливый на пеку - было бы норм

**Comment by nagayev** [comment]
@Peytob про клиент не понял.
Есть киент кора?
Т.е можно играть без браузера?

**Comment by Peytob** [comment]
Был. Могу нарыть у старожил, вроде а тапка был. Может его привлечем, кстати?

**Comment by Peytob** [comment]
Получил клиента установщик. Должен 600 МБ он докачать еще. Скоро посмотрим что он в себе имеет

**Comment by nagayev** [comment]
@Peytob отлично!
скинешь ссылку на клиент?
можно привлечь, лишним не будет.

**Comment by Peytob** [comment]
http://файлообменник.рф/hlz74odflj98.html
Попробую как бы невзначай...

**Comment by nagayev** [comment]
@Peytob скачал,сегодня попробую.
Скинь свои наработки на c++.

**Comment by Peytob** [comment]
Вечером / завтра утром. Сейчас не имею доступ к тому пк.
Тапок не может, потому что слишком занят. Он пожелал нам удачи :З

**Comment by Peytob** [comment]
Я пытался придумать что еще туда засунуть. Но это вроде все, что в целом описывает игрока, кроме системных переменных
[User.txt](https://github.com/nagayev/korapi/files/1941331/User.txt)

**Comment by nagayev** [comment]
@Peytob а прога парсящая данные с сайта есть?

**Comment by Peytob** [comment]
Была о ней мысль, но сейчас нет. Просто не до этого - посмотри как часто я коммиты делаю сейчас и как часто немногим раньше... Может через недельку или после ЕГЭ :D

**Comment by nagayev** [comment]
@Peytob окей)
А я к ОГЭ готовлюсь.
Но про класс не забыл,думаю он будет к выходным

**Comment by Peytob** [comment]
ОГЭ изи. На ЕГЭ 2-я часть очень противная, там просто так не сделать обычно. Но когда как

**Comment by nagayev** [comment]
@Peytob ага, удачи нам на экзаменах.
про класс.
выпустил тестовую версию, надеюсь норм работает.

**Comment by Peytob** [comment]
Месяц до них. Русский, проф мат, инфа, физика

**Comment by nagayev** [comment]
@Peytob
О,я тоже физмат)

**Comment by nagayev** [comment]
@Peytob отлично.
А я сделал тестовый апи класс.
Пока можно отправлять пост и настроение, к выходным добавлю
еще что-нибудь.

**Comment by nagayev** [comment]
@Peytob 
Содержимое файла lottery.xml до открытия сундука:
<?xml version='1.0' encoding='utf-8'?>
<lottery action="start" status="ok"><prices key="0.1" reset="0.5"/><keys temp="1" `permanent="0"/><matrix>0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0</matrix></lottery>

**Comment by nagayev** [comment]
@Peytob А теперь логичный вопрос.
Можно ли где-то прописать чтобы трафик шел на другой сервер?
Мы бы могли подсунуть туда 100500 ключей и скажем сделать бесплатынм ключ.

**Comment by Peytob** [comment]
Хм. Открыт сундук и из него 10 праздничных тайленов.  Сердний верхний
<lottery
 
action
="
start
"
 
status
="
ok
"
>
<prices
 
key
="
0.1
"
 
reset
="
0.5
"
/
>
<keys
 
temp
="
0
"
 
permanent
="
0
"
/
>
<matrix
>
0;0;event_token-10;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0
</matrix
>
</lottery>

**Comment by nagayev** [comment]
@Peytob есть идея как это сделать!
Изменить файл hosts, как я сразу не догадался.
Слушай, а как насчет легализации клиента?
может напишем крабу что мол пилим клиент без всякого читерства и т.д
может администрация пропиарит нас хоть.
но это после того как что-то будет, сейчас надо класс делать.

**Comment by Peytob** [comment]
Не надо. Мне не нужно лишнее внимание - бложика хватает. Только при удалении всяких упоминаний меня из обсуждений и. эм. что за Collaborator? И с уходом этой штуки, ты понял
Я попробую разбить файлик логин/настроение на два файлика, если получится

**Comment by Peytob** [comment]
![214124](https://user-images.githubusercontent.com/38009435/39397125-9f4645a2-4ae9-11e8-9214-c6441509a6e7.png)
А еще мы не получим клиент, увы

**Comment by nagayev** [comment]
@Peytob 
Окей. Жаль(
Collaborator это чел,который может редактировать репозиторий вместе с автором.

**Comment by Peytob** [comment]
Рыл эту тему минут 40 и не понял - все было близко но не то. Могу ли я разбивать твои файлы js на несколько? Вынески куки и все, что с ней связано в файл1, функцию логина во второй, функцию смены настроения в третий и связать это в кучу в третьем? Давай немного ООП поделаю

**Comment by nagayev** [comment]
@Peytob по идеи ты можешь все, что и я, кроме настроек репозитория.
Т.е не можешь удалить его, сделать приватным и т.д
ооп я сам пилю, класс почти готов на ноде,лучше поизучай другую часть.
Например что там происходит внутри флеша

**Comment by nagayev** [comment]
@Peytob 
Я заболел,в ближайший день обновлений не будет.

**Comment by Peytob** [comment]
Выздоравливай давай)
Поковырял там немного флеш - игра шлет ресурсы только, как я понял, весь код происходит на сервере. В целом, то чего и следовало ожидать

**Comment by nagayev** [comment]
@Peytob спасибо,уже выздоровел)
Да,я так и думал.
У меня замечательная новость:
Я смог написать рабочий класс с синхронными запросами(раньше были
асинх,но так не удобно).
Сегодня-завтра выложу класс на ноде.

**Comment by Peytob** [comment]
Отлично. А я ничего не делал, кроме тупого скачивания текстур из игры

**Comment by nagayev** [comment]
@Peytob 
в последний момент обнаружил,что через класс пост почему-то не отправляется,
хотя код 200 в ответ приходит.
класс залил как и обещал,но он пока не работает до конца.
